name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Give execution permission to Mocha (if local install)
        run: chmod +x ./node_modules/.bin/mocha

      - name: Run Tests
        run: npx mocha tests/*.test.js

      - name: Archive test results (optional)
        if: always()
        uses: actions/upload-artifact@v3.1.3
        with:
          name: test-results
          path: ./test-results # you must generate this folder in your tests